<Connected>:
    BoxLayout:
        orientation: 'vertical'

        Label:
            text: "You are now connected " + str(app.username)
            font_size: 32
        Label:
            text: "Schedule " + str(app.schedule)
            font_size: 9
        Label:
            text: "Your RFID is: " + str(app.rfid)
            font_size: 24
        Button:
            text: "Disconnect"
            font_size: 24
            on_press: root.disconnect()
