# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20171025_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.TextField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
