# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20171025_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='appUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(auto_created=True)),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=32)),
                ('secondname', models.CharField(max_length=32)),
                ('login', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=32)),
            ],
        ),
    ]
