# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='country',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=64),
        ),
    ]
