# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20171026_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appUser',
        ),
    ]
