# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_appuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='secondname',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='login',
            field=models.EmailField(max_length=64),
        ),
    ]
