# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20171027_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64)),
                ('firstname', models.CharField(max_length=32)),
                ('secondname', models.CharField(max_length=32)),
                ('login', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
