# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20171101_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='qsubscriber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
