# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20171101_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='password',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
