# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:33
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_auto_20171101_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_created=True),
        ),
    ]
