# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20171101_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1509547407, max_length=64),
        ),
    ]
