# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20171101_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='country',
            field=models.IntegerField(blank=True, choices=[(1, 'Afghanistan'), (2, 'Albania'), (3, 'Algeria'), (4, 'American Samoa'), (5, 'Andorra'), (6, 'Angola'), (7, 'Anguilla'), (8, 'Antarctica'), (9, 'Antigua and Barbuda'), (10, 'Argentina'), (11, 'Armenia'), (12, 'Aruba'), (13, 'Australia'), (14, 'Austria'), (15, 'Azerbaijan'), (16, 'Bahamas'), (17, 'Bahrain'), (18, 'Bangladesh'), (19, 'Barbados'), (20, 'Belarus'), (21, 'Belgium'), (22, 'Belize'), (23, 'Benin'), (24, 'Bermuda'), (25, 'Bhutan'), (26, 'Bolivia'), (27, 'Bosnia and Herzegovina'), (28, 'Botswana'), (29, 'Bouvet Island'), (30, 'Brazil'), (31, 'British Indian Ocean Territory'), (32, 'Brunei Darussalam'), (33, 'Bulgaria'), (34, 'Burkina Faso'), (35, 'Burundi'), (36, 'Cambodia'), (37, 'Cameroon'), (38, 'Canada'), (39, 'Cape Verde'), (40, 'Cayman Islands'), (41, 'Central African Republic'), (42, 'Chad'), (43, 'Chile'), (44, 'China'), (45, 'Christmas Island'), (46, 'Cocos (Keeling) Islands'), (47, 'Colombia'), (48, 'Comoros'), (49, 'Congo'), (50, 'Cook Islands'), (51, 'Costa Rica'), (52, 'Croatia (Hrvatska)'), (53, 'Cuba'), (54, 'Cyprus'), (55, 'Czech Republic'), (56, 'Denmark'), (57, 'Djibouti'), (58, 'Dominica'), (59, 'Dominican Republic'), (60, 'East Timor'), (61, 'Ecuador'), (62, 'Egypt'), (63, 'El Salvador'), (64, 'Equatorial Guinea'), (65, 'Eritrea'), (66, 'Estonia'), (67, 'Ethiopia'), (68, 'Falkland Islands (Malvinas)'), (69, 'Faroe Islands'), (70, 'Fiji'), (71, 'Finland'), (72, 'France'), (73, 'France, Metropolitan'), (74, 'French Guiana'), (75, 'French Polynesia'), (76, 'French Southern Territories'), (77, 'Gabon'), (78, 'Gambia'), (79, 'Georgia'), (80, 'Germany'), (81, 'Ghana'), (82, 'Gibraltar'), (83, 'Guernsey'), (84, 'Greece'), (85, 'Greenland'), (86, 'Grenada'), (87, 'Guadeloupe'), (88, 'Guam'), (89, 'Guatemala'), (90, 'Guinea'), (91, 'Guinea-Bissau'), (92, 'Guyana'), (93, 'Haiti'), (94, 'Heard and Mc Donald Islands'), (95, 'Honduras'), (96, 'Hong Kong'), (97, 'Hungary'), (98, 'Iceland'), (99, 'India'), (100, 'Isle of Man'), (101, 'Indonesia'), (102, 'Iran (Islamic Republic of)'), (103, 'Iraq'), (104, 'Ireland'), (105, 'Israel'), (106, 'Italy'), (107, 'Ivory Coast'), (108, 'Jersey'), (109, 'Jamaica'), (110, 'Japan'), (111, 'Jordan'), (112, 'Kazakhstan'), (113, 'Kenya'), (114, 'Kiribati'), (115, 'Korea, Democratic Peoples Republic of'), (116, 'Korea, Republic of'), (117, 'Kosovo'), (118, 'Kuwait'), (119, 'Kyrgyzstan'), (120, 'Lao Peoples Democratic Republic'), (121, 'Latvia'), (122, 'Lebanon'), (123, 'Lesotho'), (124, 'Liberia'), (125, 'Libyan Arab Jamahiriya'), (126, 'Liechtenstein'), (127, 'Lithuania'), (128, 'Luxembourg'), (129, 'Macau'), (130, 'Macedonia'), (131, 'Madagascar'), (132, 'Malawi'), (133, 'Malaysia'), (134, 'Maldives'), (135, 'Mali'), (136, 'Malta'), (137, 'Marshall Islands'), (138, 'Martinique'), (139, 'Mauritania'), (140, 'Mauritius'), (141, 'Mayotte'), (142, 'Mexico'), (143, 'Micronesia, Federated States of'), (144, 'Moldova, Republic of'), (145, 'Monaco'), (146, 'Mongolia'), (147, 'Montenegro'), (148, 'Montserrat'), (149, 'Morocco'), (150, 'Mozambique'), (151, 'Myanmar'), (152, 'Namibia'), (153, 'Nauru'), (154, 'Nepal'), (155, 'Netherlands'), (156, 'Netherlands Antilles'), (157, 'New Caledonia'), (158, 'New Zealand'), (159, 'Nicaragua'), (160, 'Niger'), (161, 'Nigeria'), (162, 'Niue'), (163, 'Norfolk Island'), (164, 'Northern Mariana Islands'), (165, 'Norway'), (166, 'Oman'), (167, 'Pakistan'), (168, 'Palau'), (169, 'Palestine'), (170, 'Panama'), (171, 'Papua New Guinea'), (172, 'Paraguay'), (173, 'Peru'), (174, 'Philippines'), (175, 'Pitcairn'), (176, 'Poland'), (177, 'Portugal'), (178, 'Puerto Rico'), (179, 'Qatar'), (180, 'Reunion'), (181, 'Romania'), (182, 'Russian Federation'), (183, 'Rwanda'), (184, 'Saint Kitts and Nevis'), (185, 'Saint Lucia'), (186, 'Saint Vincent and the Grenadines'), (187, 'Samoa'), (188, 'San Marino'), (189, 'Sao Tome and Principe'), (190, 'Saudi Arabia'), (191, 'Senegal'), (192, 'Serbia'), (193, 'Seychelles'), (194, 'Sierra Leone'), (195, 'Singapore'), (196, 'Slovakia'), (197, 'Slovenia'), (198, 'Solomon Islands'), (199, 'Somalia'), (200, 'South Africa'), (201, 'South Georgia South Sandwich Islands'), (202, 'Spain'), (203, 'Sri Lanka'), (204, 'St. Helena'), (205, 'St. Pierre and Miquelon'), (206, 'Sudan'), (207, 'Suriname'), (208, 'Svalbard and Jan Mayen Islands'), (209, 'Swaziland'), (210, 'Sweden'), (211, 'Switzerland'), (212, 'Syrian Arab Republic'), (213, 'Taiwan'), (214, 'Tajikistan'), (215, 'Tanzania, United Republic of'), (216, 'Thailand'), (217, 'Togo'), (218, 'Tokelau'), (219, 'Tonga'), (220, 'Trinidad and Tobago'), (221, 'Tunisia'), (222, 'Turkey'), (223, 'Turkmenistan'), (224, 'Turks and Caicos Islands'), (225, 'Tuvalu'), (226, 'Uganda'), (227, 'Ukraine'), (228, 'United Arab Emirates'), (229, 'United Kingdom'), (230, 'United States'), (231, 'United States minor outlying islands'), (232, 'Uruguay'), (233, 'Uzbekistan'), (234, 'Vanuatu'), (235, 'Vatican City State'), (236, 'Venezuela'), (237, 'Vietnam'), (238, 'Virgin Islands (British)'), (239, 'Virgin Islands (U.S.)'), (240, 'Wallis and Futuna Islands'), (241, 'Western Sahara'), (242, 'Yemen'), (243, 'Zaire'), (244, 'Zambia'), (245, 'Zimbabwe')], null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1510830638),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='secondName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
