# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_auto_20171116_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1510833149),
        ),
    ]
