# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_auto_20171209_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.BigIntegerField()),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('end_value', models.FloatField(blank=True, null=True)),
                ('difference', models.FloatField(blank=True, null=True)),
                ('current_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_meter_id', models.BigIntegerField()),
                ('date_of_creation', models.DateField(blank=True, null=True)),
                ('pulses_per_hour', models.IntegerField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_meter_id', models.BigIntegerField()),
                ('type_meter_name', models.CharField(max_length=32)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('metric_id', models.BigIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Subscriber_Meter',
            new_name='SubscriberMeter',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1512839488),
        ),
    ]
