# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_auto_20171209_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meter',
        ),
        migrations.DeleteModel(
            name='SubscriberMeter',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1512843579),
        ),
    ]
