# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_auto_20171209_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_meter_id', models.BigIntegerField()),
                ('date_of_creation', models.DateField(blank=True, null=True)),
                ('pulses_per_hour', models.IntegerField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('subscriber_id', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1512843590),
        ),
    ]
