# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_auto_20171216_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1513378707),
        ),
    ]
