# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_auto_20171216_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='FF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_meter_name', models.CharField(max_length=32)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('metric_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
        migrations.DeleteModel(
            name='TypeMeter',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1513416548),
        ),
    ]
