# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_auto_20171216_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FF',
            new_name='TypeMeter',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1513416566),
        ),
    ]
