# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_auto_20171216_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='subscriber_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='type_meter_id',
            field=models.BigIntegerField(blank=True, choices=[(1, 'Вода'), (2, 'Газ'), (3, 'Электричество'), (4, 'Тепло')], null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1513417399),
        ),
    ]
