# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_auto_20171216_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='recognized_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1513438081),
        ),
    ]
