# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_auto_20171216_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historymeter',
            old_name='min_value',
            new_name='start_value',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1513453282),
        ),
    ]
