# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0049_auto_20171216_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historymeter',
            old_name='current_date',
            new_name='currentdate',
        ),
        migrations.AddField(
            model_name='historymeter',
            name='money_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.IntegerField(default=1513689610),
        ),
    ]
