# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0051_auto_20180428_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('b2b7ea6e-4af6-11e8-8824-00005ae48f95'), max_length=256),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524928405),
        ),
    ]
