# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0055_auto_20180428_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='id',
        ),
        migrations.AddField(
            model_name='audience',
            name='audience_id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524953008),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('fb64f1ac-4b2f-11e8-b36b-00005ae4efb0'), max_length=256),
        ),
    ]
