# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0056_auto_20180429_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiencep',
            fields=[
                ('audience_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('audience_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Audience',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524953146),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('4d5236ca-4b30-11e8-a20d-00005ae4f03a'), max_length=256),
        ),
    ]
