# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0057_auto_20180429_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tes',
            fields=[
                ('tes_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tes_code', models.CharField(max_length=2)),
                ('tes_name', models.TextField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Audiencep',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524953295),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('a67fea5a-4b30-11e8-a815-00005ae4f0cf'), max_length=256),
        ),
    ]
