# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0058_auto_20180429_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Tes',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524953366),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('d04ee566-4b30-11e8-b7ab-00005ae4f116'), max_length=256),
        ),
    ]
