# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0059_auto_20180429_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524953368),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('d1f1de82-4b30-11e8-971b-00005ae4f118'), max_length=256),
        ),
    ]
