# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0060_auto_20180429_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524953370),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('d340e540-4b30-11e8-9cfa-00005ae4f11a'), max_length=256),
        ),
    ]
