# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0061_auto_20180429_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('classroom_name', models.TextField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Audience',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524953830),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('e5722dcc-4b31-11e8-b1de-00005ae4f2e6'), max_length=256),
        ),
    ]
