# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0062_auto_20180429_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524953833),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('e739c8b0-4b31-11e8-a702-00005ae4f2e9'), max_length=256),
        ),
    ]
