# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0064_auto_20180429_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524953891),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('09972a26-4b32-11e8-8483-00005ae4f323'), max_length=256),
        ),
    ]
