# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0065_auto_20180429_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524953982),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('400a646c-4b32-11e8-abf3-00005ae4f37e'), max_length=256),
        ),
    ]
