# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0066_auto_20180429_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524954108),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('8b0d1ed0-4b32-11e8-8b05-00005ae4f3fc'), max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.BigIntegerField(blank=True, choices=[(0, '102'), (11, '100')], null=True),
        ),
    ]
