# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0067_auto_20180429_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524954200),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('c1d37142-4b32-11e8-8951-00005ae4f458'), max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.CharField(blank=True, choices=[(0, '102'), (11, '100')], max_length=256, null=True),
        ),
    ]
