# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0068_auto_20180429_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524954246),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('dd077e64-4b32-11e8-9217-00005ae4f486'), max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.IntegerField(blank=True, choices=[(0, '102'), (11, '100')], null=True),
        ),
    ]
