# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0069_auto_20180429_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524954248),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('de9a70e2-4b32-11e8-ba4a-00005ae4f488'), max_length=256),
        ),
    ]
