# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0070_auto_20180429_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524954514),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('7cafb068-4b33-11e8-a601-00005ae4f592'), max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='isPassed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
