# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0071_auto_20180429_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524954568),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('9cd15076-4b33-11e8-9256-00005ae4f5c8'), max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
