# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0072_auto_20180429_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524954611),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('b6f2b1ae-4b33-11e8-8e3c-00005ae4f5f3'), max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
