# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0073_auto_20180429_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524954757),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('0d67f270-4b34-11e8-b047-00005ae4f685'), max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
