# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0074_auto_20180429_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524954788),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('1fe7072e-4b34-11e8-b857-00005ae4f6a4'), max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
