# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0075_auto_20180429_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524955970),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('e0f00c8c-4b36-11e8-b9e9-00005ae4fb42'), max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Two')], default=1),
        ),
    ]
