# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0076_auto_20180429_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524956320),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('b142319c-4b37-11e8-a4f8-00005ae4fca0'), max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1),
        ),
    ]
