# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0077_auto_20180429_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524956872),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('fa157826-4b38-11e8-b55e-00005ae4fec8'), max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='isPassed',
            field=models.BooleanField(editable=False),
        ),
    ]
