# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0078_auto_20180429_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524956901),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('0b573d8a-4b39-11e8-986a-00005ae4fee5'), editable=False, max_length=256),
        ),
    ]
