# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0079_auto_20180429_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524956952, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('2a452806-4b39-11e8-80c5-00005ae4ff18'), editable=False, max_length=256),
        ),
    ]
