# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0083_auto_20180429_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524957335, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('0e7ba48c-4b3a-11e8-89a9-00005ae50097'), editable=False, max_length=256),
        ),
    ]
