# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0084_auto_20180429_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('audience_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('audience_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524957364, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('1f7c3d98-4b3a-11e8-8ffa-00005ae500b4'), editable=False, max_length=256),
        ),
    ]
