# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0086_auto_20180429_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='audience_id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524957495, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('6de42a1c-4b3a-11e8-b18e-00005ae50137'), editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.IntegerField(blank=True, choices=[(0, '202')], null=True),
        ),
    ]
