# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0087_auto_20180429_0218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audience',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524957531, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('8369da70-4b3a-11e8-8425-00005ae5015b'), editable=False, max_length=256),
        ),
    ]
