# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0088_auto_20180429_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_id', models.BigIntegerField(auto_created=True)),
                ('audience_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524957543, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('8a0ea142-4b3a-11e8-a9d0-00005ae50167'), editable=False, max_length=256),
        ),
    ]
