# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0090_auto_20180429_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audience',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524957664, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('d22e4e78-4b3a-11e8-aacb-00005ae501e0'), editable=False, max_length=256),
        ),
    ]
