# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0091_auto_20180429_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('audience_id', models.AutoField(primary_key=True, serialize=False)),
                ('audience_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524957679, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('db3527a8-4b3a-11e8-bb3e-00005ae501ef'), editable=False, max_length=256),
        ),
    ]
