# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0093_auto_20180429_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='audience_name',
        ),
        migrations.AlterField(
            model_name='audience',
            name='audience_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1524978925, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('52d8149e-4b6c-11e8-af93-00005ae554ed'), editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.IntegerField(blank=True, choices=[({'audience_id': 1}, {'audience_id': 1})], null=True),
        ),
    ]
