# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0094_auto_20180429_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525007082, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('e1ea26d0-4bad-11e8-8114-00005ae5c2ea'), editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.IntegerField(blank=True, choices=[((0,), (0,)), ((10,), (10,)), ((1,), (1,)), ((2,), (2,))], null=True),
        ),
    ]
