# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0096_auto_20180429_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525007825, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('9ca0fea4-4baf-11e8-a3d6-00005ae5c5d1'), editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.IntegerField(blank=True, choices=[({'audience_id': 0}, {'audience_id': 0}), ({'audience_id': 10}, {'audience_id': 10}), ({'audience_id': 1}, {'audience_id': 1}), ({'audience_id': 2}, {'audience_id': 2})], null=True),
        ),
    ]
