# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0097_auto_20180429_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525007848, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('aa3f98ac-4baf-11e8-9e64-00005ae5c5e8'), editable=False, max_length=256),
        ),
    ]
