# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0098_auto_20180429_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525007987, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('fd388dd4-4baf-11e8-b25e-00005ae5c673'), editable=False, max_length=256),
        ),
    ]
