# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0099_auto_20180429_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525008015, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('0e206ae4-4bb0-11e8-9d0e-00005ae5c68f'), editable=False, max_length=256),
        ),
    ]
