# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0100_auto_20180429_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525008194, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('786214ca-4bb0-11e8-a185-00005ae5c742'), editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.IntegerField(blank=True, choices=[((0,), (0,)), ((10,), (10,)), ((1,), (1,)), ((2,), (2,))], null=True),
        ),
    ]
