# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0101_auto_20180429_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525008218, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('8706dac8-4bb0-11e8-9475-00005ae5c75a'), editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.IntegerField(blank=True, choices=[(None, (0,)), (None, (10,)), (None, (1,)), (None, (2,))], null=True),
        ),
    ]
