# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0102_auto_20180429_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525008555, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('4fdc0d78-4bb1-11e8-8798-00005ae5c8ab'), editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.IntegerField(blank=True, choices=[({'audience_id': 0}, {'audience_id': 0}), ({'audience_id': 10}, {'audience_id': 10}), ({'audience_id': 1}, {'audience_id': 1}), ({'audience_id': 2}, {'audience_id': 2})], null=True),
        ),
    ]
