# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0105_auto_20180429_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525009338, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('22b6e1a8-4bb3-11e8-8ee4-00005ae5cbba'), editable=False, max_length=256),
        ),
    ]
