# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0106_auto_20180429_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525009463, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('6cd2a862-4bb3-11e8-9865-00005ae5cc37'), editable=False, max_length=256),
        ),
    ]
