# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0110_auto_20180429_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525024612, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('b24610fa-4bd6-11e8-9cb1-00005ae60764'), editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.IntegerField(blank=True, choices=[(10, 10), (0, 0)], null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='isPassed',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
