# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0111_auto_20180429_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='isPassed',
            new_name='is_passed',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525024865, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('4961831c-4bd7-11e8-924e-00005ae60861'), editable=False, max_length=256),
        ),
    ]
