# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0114_auto_20180429_2301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audience',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525079756, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('16ca76be-4c57-11e8-b4f2-00005ae6decc'), editable=False, max_length=256),
        ),
    ]
