# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0115_auto_20180430_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525079989, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('a1efc26c-4c57-11e8-b726-00005ae6dfb5'), editable=False, max_length=256),
        ),
    ]
