# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0117_auto_20180430_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'), (6, 'six')], default=1)),
                ('audience_name', models.IntegerField(blank=True, null=True)),
                ('day', models.DateField(blank=True, null=True)),
                ('lecturer', models.CharField(blank=True, choices=[('b8115390-4af6-11e8-996a-00005ae48f9e', 'Qwe'), ('e8b56168-4b0f-11e8-ac7f-00005ae4b9e1', 'qaz')], max_length=256, null=True)),
                ('is_passed', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525080088, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('dcb40a30-4c57-11e8-8ae2-00005ae6e018'), editable=False, max_length=256),
        ),
    ]
