# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0118_auto_20180430_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='audience_name',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525080174, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('0ffa90b6-4c58-11e8-b802-00005ae6e06e'), editable=False, max_length=256),
        ),
    ]
