# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0119_auto_20180430_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525090395, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('dc1a384c-4c6f-11e8-94ee-00005ae7085b'), editable=False, max_length=256),
        ),
    ]
