# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0120_auto_20180430_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525090769, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('bb772c12-4c70-11e8-b4f5-00005ae709d1'), editable=False, max_length=256),
        ),
    ]
