# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0122_auto_20180430_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525165348, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('5f81c32c-4d1e-11e8-8792-00005ae82d24'), editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.IntegerField(blank=True, choices=[(102, 102), (106, 106), (108, 108), (110, 110), (112, 112), (114, 114)], null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecturer',
            field=models.CharField(blank=True, choices=[('7d4b47e8-4c8d-11e8-baa1-00005ae73a11', 'Qwe'), ('0308fc62-4d13-11e8-a188-00005ae81a14', '1'), ('723fc178-4d1c-11e8-ab13-00005ae829e8', 'Qaz')], max_length=256, null=True),
        ),
    ]
