# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0123_auto_20180501_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='created_at',
            field=models.IntegerField(default=1525172548, editable=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rfid',
            field=models.CharField(default=uuid.UUID('237ce5e6-4d2f-11e8-9b9f-00005ae84944'), editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audience_name',
            field=models.IntegerField(blank=True, choices=[(102, 102), (106, 106), (108, 108), (110, 110), (130, 130), (120, 120)], null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecturer',
            field=models.CharField(blank=True, choices=[('7d4b47e8-4c8d-11e8-baa1-00005ae73a11', 'Qwe')], max_length=256, null=True),
        ),
    ]
